/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class MainForm extends javax.swing.JFrame {
    public CardLayout mainLayout;
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        mainPanel.setLayout(new CardLayout());
        mainPanel.add(filePanel, "fp");
        mainPanel.add(editPanel, "ep");
        mainLayout = (CardLayout)mainPanel.getLayout();
        mainLayout.show(mainPanel, "fp");
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        editPanel = new javax.swing.JPanel();
        filePanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mnEdit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setLayout(new java.awt.CardLayout());

        editPanel.setBackground(new java.awt.Color(255, 153, 51));

        javax.swing.GroupLayout editPanelLayout = new javax.swing.GroupLayout(editPanel);
        editPanel.setLayout(editPanelLayout);
        editPanelLayout.setHorizontalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );
        editPanelLayout.setVerticalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        mainPanel.add(editPanel, "card3");

        filePanel.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout filePanelLayout = new javax.swing.GroupLayout(filePanel);
        filePanel.setLayout(filePanelLayout);
        filePanelLayout.setHorizontalGroup(
            filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );
        filePanelLayout.setVerticalGroup(
            filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        mainPanel.add(filePanel, "card2");

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        mnFile.setText("File");
        mnFile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnFile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnFile.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        mnFile.setIconTextGap(0);
        mnFile.setMargin(new java.awt.Insets(0, 0, 0, 0));
        mnFile.setMaximumSize(new java.awt.Dimension(80, 32767));
        mnFile.setMinimumSize(new java.awt.Dimension(80, 31));
        mnFile.setPreferredSize(new java.awt.Dimension(80, 31));
        mnFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnFileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnFileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mnFileMouseExited(evt);
            }
        });
        mnFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFileActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnFile);

        mnEdit.setText("Edit");
        mnEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnEdit.setMaximumSize(new java.awt.Dimension(80, 32767));
        mnEdit.setPreferredSize(new java.awt.Dimension(80, 31));
        mnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnEditMouseClicked(evt);
            }
        });
        mnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEditActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnEdit);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFileActionPerformed

    }//GEN-LAST:event_mnFileActionPerformed

    private void mnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEditActionPerformed

    }//GEN-LAST:event_mnEditActionPerformed

    private void mnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnEditMouseClicked
        mainLayout.show(mainPanel,"ep");
    }//GEN-LAST:event_mnEditMouseClicked

    private void mnFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnFileMouseClicked
        mainLayout.show(mainPanel,"fp");
    }//GEN-LAST:event_mnFileMouseClicked

    private void mnFileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnFileMouseEntered
        mnFile.setOpaque(true);
        mnFile.setBackground(Color.blue);
    }//GEN-LAST:event_mnFileMouseEntered

    private void mnFileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnFileMouseExited
        mnFile.setOpaque(false);
        mnFile.setBackground(Color.WHITE);
    }//GEN-LAST:event_mnFileMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel editPanel;
    private javax.swing.JPanel filePanel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenu mnEdit;
    private javax.swing.JMenu mnFile;
    // End of variables declaration//GEN-END:variables
}
